### ISSUE TITLE
Small breaking change in vbox 7

### ISSUE THREAD

**Issue by damzog** [cloudfoundry/bosh-virtualbox-cpi-release#30]
Hi,

while trying to setup bosh lite with virtualbox 7 I found that the NatNetwork is not discovered. I think it is because the command VBoxManage list networks has sligthly changed the output format: The network name used to printed as e.g. "NetworkName: NatNetwork". In virtualbox 7 it is "Name: NatNetwork". Therefore it seems that the following code does not find the adapter for the NatNetwork anymore: https://github.com/cloudfoundry/bosh-virtualbox-cpi-release/blob/dc23b79ba6ad2f65b0a42eeeb35b95c2e0339948/src/bosh-virtualbox-cpi/vm/host.go#L74

See also 
![vbox-6](https://github.com/cloudfoundry/bosh-virtualbox-cpi-release/assets/16135207/22d3b64b-32d3-4cf5-afc6-2904ca6761ab)
![vbox-7](https://github.com/cloudfoundry/bosh-virtualbox-cpi-release/assets/16135207/f174b5b3-70aa-4c20-a75f-df7fe17dbe48)

**Comment by ramonskie** [comment]
if you think you found the issue and fixed the code you could create a dev release
`bosh create-release --force --tarball=virtualbox-cpi.tgz`
and then use an ops file with the follwoing to overwrite the virutalbox cpi
```
- name: cpi
  path: /releases/name=bosh-vritualbox-cpi
  type: replace
  value:
    name: bosh-aws-cpi
    url: file:///home/USERNAME/workspace/bosh/bosh-aws-cpi-release/vrtualbox-cpi.tgz
    version: latest
```

**Comment by damzog** [comment]
@ramonskie thanks for the hint. I worked around the issue by downgrading to vbox 6 which seems to work. However I am facing other issues but this is a different story. I just wanted to note this issue for the records. So if someone happens to do some maintenance work on the cpi he might take a look at it. Finally I managed to upload the images from my private network (from company network it did not work probably because of https://github.com/orgs/community/discussions/28947 ). You can see that also other attribute names were changed. So it might be a little bit of work to make it run.

**Comment by chombium** [comment]
I've started working on this issue and I have a working PoC with VBox 7. The output from the  [VBox CLI call](https://github.com/cloudfoundry/bosh-virtualbox-cpi-release/blob/master/src/bosh-virtualbox-cpi/vm/network/networks.go#L45) for listing the NAT Networks was changed and now instead of the used one, a new `VBoxManage natnetwork list` should be used and the parsing of the output should be adjusted.

I'm planning to do the changes for VBox 7 and VBox 6.1 as the other Older VBox versions are out of maintenance.

@rkoster can you please assign this issue to me. I cannot do it myself.

**Comment by chombium** [comment]
Thank you very much @ramonskie

**Comment by beyhan** [comment]
Sounds great! We would love to review a pr.

**Comment by chombium** [comment]
Hi, I've opened a draft PR so that you can see our progress. 
We've fixed the NAT Network parsing without breaking the backward compatibility (VBox newer than v6.1).

Up until now we've tested everything on Linux and we're doing tests on MacOS as well. @ZPascal is still testing some things on MacOS where we might need to do some extra changes.
We don't have Windows at hand and we don't know if we should test this on Windows. If so, it would be nice if someone can validate if everything is working properly.


## Testing:

### Clone needed repos:
- [bosh-deployment](https://github.com/cloudfoundry/bosh-deployment)
- Check out the [network-param-name](https://github.com/chombium/bosh-virtualbox-cpi-release/tree/network-param-name) branch from our repo

- build a release from the `bosh-virtualbox-cpi-recreate`
```
bosh create-release --force --tarball=virtualbox-cpi.tgz
```
- cpi.yml (adjust the path to the release archive)
```yaml
- name: cpi
  path: /releases/name=bosh-virtualbox-cpi
  type: replace
  value:
    name: bosh-virtualbox-cpi
    url: file:///path/to/virtualbox-cpi.tgz
    version: latest
```

```
export BOSH_DEV=/path/to/bosh-deployment
bosh create-env $BOSH_DEV/bosh.yml \
  --state ./state.json \
  -o $BOSH_DEV/virtualbox/cpi.yml \
  -o ./cpi.yml \
  -o $BOSH_DEV/virtualbox/outbound-network.yml \
  -o $BOSH_DEV/bosh-lite.yml \
  -o $BOSH_DEV/bosh-lite-runc.yml \
  -o $BOSH_DEV/uaa.yml \
  -o $BOSH_DEV/credhub.yml \
  -o $BOSH_DEV/jumpbox-user.yml \
  --vars-store ./creds.yml \
  -v director_name=bosh-lite \
  -v internal_ip=192.168.56.6 \
  -v internal_gw=192.168.56.1 \
  -v internal_cidr=192.168.56.0/24 \
  -v outbound_network_name=NatNetwork
```

**Comment by chombium** [comment]
The problem on MacOS is a bit bigger. They've changed the commands to list host only interfaces.
The `VBoxManage list hostonlyifs` command that worked before doesn't work anymore on MacOS, but still works on Linux. One should use `VBoxManage list hostonlynets` command on MacOS, which is unknown on Linux `VBoxManage: error: Unknown subcommand "hostonlynets".`

We'll have to add some checks about the OS that the CPI is working on and execute the right command, which will take us some more time.  :-/ 

@ZPascal is working on it.

**Comment by ZPascal** [comment]
I modified the corresponding code base to fix the MAC OS X-related issues, and I've already tested it on my end using the Jammy-based Zookeeper version and running the corresponding Smoke tests. The Bosh Lite setup now works as expected. You can download the tar archive of the new release [here](https://sap-my.sharepoint.com/:u:/p/pascal_zimmermann01/EalSBdMgSgZGjgtISyCqSBoBZRTVh1YZjABAT46MZ5P-1w?e=GaQ3Vl) and use it for your tests. Please report any related issues. Thank you.

**Comment by ZPascal** [comment]
Hi everyone,

I am having some issues related to the VirtualBox 6.1 test case on Mac OS X. I can't fully test it because my Mac OS X is too new and it is not possible to install the necessary kernel modules on my system.
I have checked the available commands and [adjusted](https://github.com/cloudfoundry/bosh-virtualbox-cpi-release/pull/31/commits/db11c879a2fbdc042ac3a094e8e30349c2e13d6d) the function in general, but for me, it is not possible to test version 6.1 together with a current Mac OS X system. If someone got an old Mac system, that would be nice if the person could validate the functionality.

Oracle's official support also [ends](https://www.virtualbox.org/wiki/Downloads) at the end of the year, so I wonder if it is really necessary to support VBox 6.1 on Mac OS X?

**Comment by ZPascal** [comment]
I've organised an Windows 11 device and we've performed the setup on the corresponding device. For my understanding it's since 2018 not possible to use Bosh Lite under Windows, because we've faced the following issue. From my understanding, we can't fix that, because since years it's not [possible](https://github.com/cloudfoundry/bosh-utils/blame/v0.0.385/system/exec_cmd_runner.go#L87-L89) to execute the `create-env` command on Windows.

**Comment by wayneeseguin** [comment]
Does that include running from WSL?

**Comment by ZPascal** [comment]
> Does that include running from WSL?

No, we've tested the native Windows functionality.

**Comment by chombium** [comment]
Hi @wayneeseguin when a program runs on Windows under WSL `runtime.GOOS = linux`, hence, the BOSH VirtualBox CPI should behave the same as on native Linux. TBH, I don't have a Windows machine to test, but I suppose it will work.
